# Heart disease prediction with classification

In [3]:
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd

In [6]:
# import data
df_heart = pd.read_csv("data_heart_disease/heart-disease.csv")

In [7]:
df_heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [9]:
df_heart.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0

In [10]:
df_heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [11]:
df_heart.shape

(303, 14)

In [12]:
df_heart.nunique()

age          41
sex           2
cp            4
trestbps     49
chol        152
fbs           2
restecg       3
thalach      91
exang         2
oldpeak      40
slope         3
ca            5
thal          4
target        2
dtype: int64

In [14]:
df_heart.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

## Checkinig the data

In [15]:
df_heart.duplicated().sum()

1

In [17]:
df_heart = df_heart.drop_duplicates()

In [18]:
df_heart.duplicated().sum()

0

In [19]:
df_heart.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [20]:
# defining X and y 
X =  df_heart.drop("target", axis=1)
y = df_heart['target']

In [21]:
#  spiltting  data into data train and testing 
from sklearn.model_selection import  train_test_split

X_train, X_test, y_train,  y_test = train_test_split(X,y)

In [22]:
#  showing shapes of spilltted data
 
X_train.shape, X_test.shape, y_train.shape,  y_test.shape 

((226, 13), (76, 13), (226,), (76,))

## Model estimator

In [23]:
from sklearn.ensemble import RandomForestClassifier
model_randomforest = RandomForestClassifier()

In [24]:
# fitting model 

model_randomforest.fit(X_train, y_train)

RandomForestClassifier()

In [25]:
# make a predicitions 
y_preds = model_randomforest.predict(X_test)

In [26]:
y_preds

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [27]:
X_test.loc[206]

age          59.0
sex           1.0
cp            0.0
trestbps    110.0
chol        239.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
Name: 206, dtype: float64

In [29]:
df_heart.loc[206]

age          59.0
sex           1.0
cp            0.0
trestbps    110.0
chol        239.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
target        0.0
Name: 206, dtype: float64

In [30]:

# Make a prediction on a single sample (has to be array)
model_randomforest.predict(np.array(X_test.loc[206]).reshape(1, -1))

c:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [31]:
# ealuate a models 
model_randomforest.score(X_train, y_train)

1.0

In [32]:

# On the test set (unseen)
model_randomforest.score(X_test, y_test)

0.8947368421052632

In [33]:

# Try different numbers of estimators (n_estimators is a hyperparameter you can change)
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model_randomforest2 = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model_randomforest2.score(X_test, y_test)}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.8157894736842105

Trying model with 20 estimators...
Model accruacy on test set: 0.8421052631578947

Trying model with 30 estimators...
Model accruacy on test set: 0.8421052631578947

Trying model with 40 estimators...
Model accruacy on test set: 0.8552631578947368

Trying model with 50 estimators...
Model accruacy on test set: 0.8421052631578947

Trying model with 60 estimators...
Model accruacy on test set: 0.8421052631578947

Trying model with 70 estimators...
Model accruacy on test set: 0.881578947368421

Trying model with 80 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 90 estimators...
Model accruacy on test set: 0.868421052631579



In [34]:

from sklearn.model_selection import cross_val_score

# Try different numbers of estimators with cross-validation and no cross-validation
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model_randomforest3 = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model_randomforest3.score(X_test, y_test)}")
    print(f"Cross-validation score: {np.mean(cross_val_score(model_randomforest3, X, y, cv=5)) * 100}%")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 77.80327868852459%

Trying model with 20 estimators...
Model accruacy on test set: 0.8289473684210527
Cross-validation score: 78.47540983606557%

Trying model with 30 estimators...
Model accruacy on test set: 0.868421052631579
Cross-validation score: 81.43169398907105%

Trying model with 40 estimators...
Model accruacy on test set: 0.881578947368421
Cross-validation score: 79.44808743169398%

Trying model with 50 estimators...
Model accruacy on test set: 0.8289473684210527
Cross-validation score: 82.08196721311477%

Trying model with 60 estimators...
Model accruacy on test set: 0.8289473684210527
Cross-validation score: 80.77595628415301%

Trying model with 70 estimators...
Model accruacy on test set: 0.8421052631578947
Cross-validation score: 82.09836065573771%

Trying model with 80 estimators...
Model accruacy on test set: 0.868421052631579
Cross-validation score: 81.437158469945

In [ ]:
# saving model for later used
import pickle
# save a traines model
pickle.dump(model_randomforest, open("random_forest_model_1.pkl", "wb"))

In [36]:
# Load a saved model and make a prediction on a single example
loaded_model_random_forest = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model_random_forest.predict(np.array(X_test.loc[206]).reshape(1, -1))

c:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)